### ISSUE TITLE
Move report.Rmd?

### ISSUE THREAD

**Issue by bpbond** [tiernanmartin/drakepkg#7]
I see that `report.Rmd` is in `inst/doc`, but this folder is deleted by the default RStudio build step; see https://github.com/r-lib/pkgbuild/issues/58. 

Does this not happen when you build this package? 😕  Perhaps consider moving the report files to e.g. `inst/reports`? Thanks.

**Comment by tiernanmartin** [comment]
You're right - thanks for providing the link to the underlying issue.

I replaced `report.Rmd` with two similar docs that now live in the `documents` directory. Users can generate these document from scratch by following the steps listed in the README.
